### ISSUE TITLE
Using locally stored images

### ISSUE THREAD

**Issue by aubreywullschleger** [kkrishnak/prj-rev-bwfs-tea-cozy#3]
Great! Nice job using locally stored images for your project! This is best practice for production code and helps your page load faster. 

Example: https://github.com/kkrishnak/prj-rev-bwfs-tea-cozy/blob/master/Tea%20Cozy/index.html#L29

Make sure to use descriptive `alt` attributes on all of your `<img>` elements like this: `<img src="./resources/img-berryblitz.jpg" alt="mug of tea with berries"/>` This is best practice and helps make your site even more accessible!

**Comment by kkrishnak** [comment]
<!DOCTYPE html>
<html>
<head>
	<title>Tea Cozy</title>
	<link href="./resources/style.css" type="text/css" rel="stylesheet">
</head>
<body>
<header class="flex-container">
  <img src="./resources/img-tea-cozy-logo.png" />
<nav>
  <span><a href="#link1">Mission</a></span>
  <span><a href="#link2">Featured Tea</a></span>
  <span><a href="#link3">Locations</a></span>
</nav>
</header>
<div id="link1">
<div class="center">
<div class="center-text">
  <h2>Our Mission</h2>
  <h4>Handpicked, Artisanally Curated, Free Range, Sustainable, Small Batch, Fair Trade, Organic Tea</h4>
</div>
</div>
</div>
<div id="link2">
  <h2>Tea of the Month</h2>
  <h4>What's Steeping at The Tea Cozy?</h4>
<div class="flex-container items">
<div class="item">
  <img src="./resources/img-berryblitz.jpg" alt="mug of tea with berries"/> 
  <span>Fall Berry Blitz Tea</span>
</div>
<div class="item">
  <img src="./resources/img-spiced-rum.jpg" alt="A box with a Message"/> 
  <span>Spiced Rum Tea</span>
</div>
<div class="item">
  <img src="./resources/img-donut.jpg" alt="a yummy donut"/> 
  <span>Seasonal Donuts</span>
</div>
<div class="item">
  <img src="./resources/img-myrtle-ave.jpg" alt="mug of tea with with Pepper"/> 
  <span>Myrtle Ave Tea</span>
</div>
<div class="item">
  <img src="./resources/img-bedford-bizarre.jpg" alt="mug of tea with a sugar jar"/> 
  <span>Bedford Bizarre Tea</span>
</div>
</div>
</div>
<div id="link3">
  <h2>Locations</h2>
<div class="flex-container">
<div class="location">
  <h3>Downtown</h3>
  <p>384 West 4th St</p>
  <p>Suite 108</p>
  <p>Portland, Maine</p>
</div>
<div class="location">
  <h3>East Bayside</h3>
  <p>3433 Phisherman's Avenue</p>
  <p>(Northwest Corner)</p>
  <p>Portland, Maine</p>
</div>
<div class="location">
  <h3>Oakdale</h3>
  <p>515 Crescent Avenue</p>
  <p>Second Floor</p>
  <p>Portland, Maine</p>
</div>
</div>
</div>
<div id="#contact">
  <h2>The Tea Cozy</h2>
  <h5>contact@theteacozy.com</h5>
  <h5>917-555-8904</h5>
</div>
<footer>
  <h5>copyright The Tea Cozy 2017</h5>	
</footer>

</body>
</html>

**Comment by kkrishnak** [comment]
I made the changes with alt.
